name: Deploy
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [setup, test, lint]
    steps:
      - name: Build
        run: echo "Building..."
