name: Deploy
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node
      - name: Run tests
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node
      - name: Run lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node
      - name: Build
        run: npm run build
